name: updateEC2

on:
  push:
    branches:
      - 'main'  # 메인이 푸쉬되었을 때 동작
  pull_request:
    branches:
      - 'main'  # 메인이 pull_request 시 동작

  workflow_dispatch:
  
env:
  HOST: ${{ secrets.SERVER_SSH_HOST }}
  USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
  KEY: ${{ secrets.SERVER_SSH_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }} # 서버  ip주소
          username: ${{ env.USERNAME }} # 서버 유저이름
          key: ${{ env.KEY }} # AWS 연결 키
          script: |
            cd TTWordServer
            echo hi > test.txt


